apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-react-app
  template:
    metadata:
      labels:
        app: vite-react-app
    spec:
      containers:
        - name: vite-react-app
          image: vite-react-app:latest
          imagePullPolicy: Never # image exists locally
          ports:
            - containerPort: 80